engineStrict: true
minimumReleaseAge: 1440
publicHoistPattern:
  - '@lezer/*'
  - '@codemirror/*'
  - 'workbox-*'
  - 'vite-plugin-pwa'
allowBuilds:
  core-js: true
  es5-ext: true
  esbuild: true
  sharp: true
overrides:
  '@sveltejs/kit>cookie': 0.7.2
  svelte-i18n>esbuild: 0.28.1
