[app]
# authentication
token_expiration_hours = 120
auth_exclude_paths = ["/auth/login", "/user/count", "/user/create_admin", "/system/platform"]

# https://sanic.dev/en/guide/running/configuration.html
request_timeout = 60
response_timeout = 60
keep_alive_timeout = 120
fallback_error_format = "json"

# https://sanic.dev/en/plugins/sanic-ext/openapi/ui.html
oas_ui_redoc = false
oas_ui_default = "swagger"

[workspace]
images = "{workspace}/images"
database = "{workspace}/database"
transcoded = "{workspace}/transcoded"
repositories = "{workspace}/repositories"
